### ISSUE TITLE
QA simulation instructions

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#54]
We should QA the phase 2 simulation run script instructions and make sure that they work as intended.

**Comment by RiesBen** [comment]
I read through the instructions, and in the execution section, I'm not sure if we have a bug:
(https://industrybenchmarks2024.readthedocs.io/en/latest/public/overview.html#simulation-execution)

I think it should be:
`for file in network_setup/transformation/*.json; do`
instead of:
`for file in network_setup/*.json; do`
